version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_auth
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring_auth:
    build: .
    container_name: spring_auth_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/spring_auth?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data:
